server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: daas-resource-server
  datasource:
    ds1:
      jdbc-url: jdbc:mysql://localhost:3306/daas?serverTimezone=UTC
      username: root
      password: jdb123
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
    ds2:
      jdbc-url: jdbc:mysql://localhost:3306/daas?serverTimezone=UTC
      username: root
      password: jdb123
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 2
      min-idle: 1
      initial-size: 1
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml