server:
  port: 80
  servlet:
    context-path: /
spring:
  application:
    name: daas-authorization-server
  datasource:
    url: jdbc:mysql://localhost:3306/daas?serverTimezone=UTC
    username: root
    password: jdb123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 2
      min-idle: 1
      initial-size: 1
      connect-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJotZQ6WU88AnEMOUCeGzc3DmbNL+uGrH4U5t4FslSEv4zHa9sKsO5FZMm0WPMWXqB65gXtY/9xReGsM1dDgOIkCAwEAAQ==
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.gzhtdq.daas.security.domai,com.gzhtdq.daas.bussness.domai
